openapi: 3.0.3

info:
  title: Sweepstakes API
  description: APIs for the Sweepstakes backend
  version: 0.0.1

servers:
  - url: http://localhost/v1
    description: local development server

paths:
  #-------------------------------
  # FIXTURES
  #-------------------------------
  /tournaments/{tournamentId}/fixtures/{fixtureId}:
    parameters:
      - $ref: '#/components/parameters/tournamentIdParam'
      - $ref: '#/components/parameters/fixtureIdParam'

    get:
      summary: Returns a fixture for a tournament.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FixtureWithId'

    put:
      summary: Update a fixture of a tournament.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fixture'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FixtureWithId'

    patch:
      summary: Update a fixture of a tournament.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fixture'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FixtureWithId'

    delete:
      summary: Delete a fixture from a tournament.
      responses:
        '204':
          description: Deleted

  /tournaments/{tournamentId}/fixtures:
    parameters:
      - $ref: '#/components/parameters/tournamentIdParam'

    get:
      summary: Returns a list of fixtures for a tournament.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fixtures'

    post:
      summary: Add a fixture to a tournament.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fixture'

      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FixtureWithId'

components:
  #-------------------------------
  # Reusable schemas (data models)
  #-------------------------------
  schemas:
    Id:
      type: object
      properties:
        id:
          type: integer
      example:
        id: 4

    Fixture: # Can be referenced as '#/components/schemas/Fixture'
      type: object
      properties:
        tournament_name:
          type: string
        home_team:
          type: string
        away_team:
          type: string
        kickoff:
          type: string
          format: date-time
        home_goals:
          type: integer
        away_goals:
          type: integer
        home_penalties:
          type: integer
        away_penalties:
          type: integer
        group_stage:
          type: boolean
        # fixture_data:
      example:
        tournament_name: UEFA EURO 2020
        home_team: BEL
        away_team: ITA
        kickoff: 12-06-2020
        home_goals: 0
        away_goals: 0
        home_penalties:
        away_penalties:
        group_stage: true

    FixtureWithId: # Can be referenced as '#/components/schemas/FixtureWithId'
      allOf:
        - $ref: '#/components/schemas/Id'
        - $ref: '#/components/schemas/Fixture'
        # - type: object
        #   properties:
        #     id:
        #       type: integer
      example:
        id: 4
        tournament_name: UEFA EURO 2020
        home_team: BEL
        away_team: ITA
        kickoff: 12-06-2020
        home_goals: 0
        away_goals: 0
        home_penalties:
        away_penalties:
        group_stage: true

    Fixtures: # Can be referenced as '#/components/schemas/Fixtures'
      type: array
      items:
        $ref: '#/components/schemas/FixtureWithId'
      example:
        - id: 4
          tournament_name: UEFA EURO 2020
          home_team: BEL
          away_team: ITA
          kickoff: 12-06-2020
          home_goals: 1
          away_goals: 0
          home_penalties:
          away_penalties:
          group_stage: true
        - id: 5
          tournament_name: UEFA EURO 2020
          home_team: GER
          away_team: NLD
          kickoff: 13-06-2020
          home_goals: 1
          away_goals: 3
          home_penalties:
          away_penalties:
          group_stage: true

  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    tournamentIdParam: # Can be referenced via '#/components/parameters/tournamentIdParam'
      name: tournamentId
      in: path
      description: Tournament Identifier for which you want to see the fixtures
      required: true
      schema:
        type: integer
        minimum: 0

    fixtureIdParam: # Can be referenced via '#/components/parameters/fixtureIdParam'
      name: fixtureId
      in: path
      description: Fixture Identifier of Fixture you want to retrieve
      required: true
      schema:
        type: integer
        minimum: 0
